name: cd

on:
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Experiment
      run: |
        pwd
        mkdir hello
        cd hello
        pwd

