name: OS and Perl Matrix

on: push

jobs:
  build:
    environment: DEPLOYMENT
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v2

      - name: View environment
        run: |
          uname -a
          printenv | sort

      - name: Build
        env:
           MYNAME: ${{ secrets.MYNAME }}
        run: |
          echo $MYNAME
          echo $MYNAME > code.txt
          ls -l
          cat code.txt

