name: Failure?

on:
    push:
        branches: '*'
    pull_request:
        branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Job

    steps:
    - uses: actions/checkout@v2

    - name: Step one
      run: ls

    - name: Run on failure
      if: ${{ failure() }}
      run: echo There was a failure

    - name: Step two
      run: |
          echo Runs if there was no failure
          ls qqrq


