name: OS Matrix

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runner: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{matrix.runner}}
    steps:
    - uses: actions/checkout@v2

    - name: View environment
      run: |
        uname -a
        printenv | sort
        perl -v

    - name: Install cpanm
      if: ${{ matrix.runner != "windows-latest" }}
      run: |
        curl -L https://cpanmin.us | perl - App::cpanminus

    - name: Install module
      run: |
        cpanm Module::Runtime
        cpanm Dancer2
